import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import TodoList from "../components/TodoList";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/list-solid.svg" />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <TodoList />
      </main>
    </div>
  );
};

export default Home;
